server:
  port: 8000
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: TRAINER-SERVICE
          uri: http://localhost:8030
          predicates:
            - Path=/api/trainers/**
        - id: EQUIPMENT-SERVICE
          uri: http://localhost:8040
          predicates:
            - Path=/api/equipment/**
        - id: MEMBER-SERVICE
          uri: http://localhost:8050
          predicates:
            - Path=/api/members/**
        - id: CLASSES-SERVICE
          uri: http://localhost:8060
          predicates:
            - Path=/api/classes/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8015/realms/gym-ApiGateway
          jwk-set-uri: http://localhost:8015/realms/gym-ApiGateway/protocol/openid-connect/certs
keycloak:
  auth-server-url: http://localhost:8015/auth
  realm: gym-ApiGateway
  resource: apigateway-service
  public-client: false
  credentials:
    secret: Ij9VE9dX0dTq9ZFwktZYlupeBjfIwtvy
logging:
  level:
    org.springframework.security: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka